### ISSUE TITLE
Creates invalid eml file

### ISSUE THREAD

**Issue by lieser** [pgpgeek/thunderbird-addon-eml-editor#1]
The current template for the eml file save by the add-on is
```
X-Unsent: 1
To: %to%
Cc: %cc%
Subject: %subject%
Content-Type: text/html; charset=UTF-8
MIME-Version: 1.0
<space><space>
%body%`
```
Note that the `<space><space>` before the body is an edit from me. In the code this are two normal spaces.

According to the RFC, there must be however a completely empty line between both messages.
https://tools.ietf.org/html/rfc5322#section-2.1:
> The body is simply a sequence of
   characters that follows the header section and is separated from the
   header section by an empty line (i.e., a line with nothing preceding
   the CRLF).

**Comment by pgpgeek** [comment]
Hi lieser,

This is now fixed (with other "minor" fix), thanks for your feedback.
[https://github.com/pgpgeek/thunderbird-addon-eml-editor/commit/5298db80f04c3077d845a8ae1b7a1ff2774f7293](url)

**Comment by lieser** [comment]
Thanks for the quick fix.
