### ISSUE TITLE
Missing

### ISSUE THREAD

**Issue by xlovinglyx** [pgpgeek/thunderbird-addon-eml-editor#2]
If not already implemented, here are probably missing options:

-sure it's missing:
X-Priority (during saving)

-if not added yet: saving attachments too,
in emls, inline or simply attached has to bed saved too.

**Comment by pgpgeek** [comment]
Hi xlovinglyx,

Yes it's a greats ideas.

**X-Priority**
I will let this issue opened because actually it's not possible with the current API, you can see here all the datas provided about the getter from message's composer :
https://thunderbird-webextensions.readthedocs.io/en/78/compose.html#composedetails

 **saving attachments**
I will try to implement it when i will have a free short moment (not really in long time)

**Comment by xlovinglyx** [comment]
thank you, and if it's not done yet:

If i leave anything in from, or in to, or cc or bcc, it should be saved too.

**Comment by pgpgeek** [comment]
`If i leave anything in from, or in to, or cc or bcc, it should be saved too.`

It's already done ;)

**Comment by pgpgeek** [comment]
As you can see here : https://github.com/pgpgeek/thunderbird-addon-eml-editor/commit/2587a917b4e7ccffd6bb48bd895e3c9ecc9a5b5e

The attachments feature is in progress ;)

**Comment by pgpgeek** [comment]
Attachements feature (on save & open) is done  :D 
You can download it on the store or juste upgrade from thunderbird ;)
Newest version is 1.3

**Comment by xlovinglyx** [comment]
I like your 1) Done 
& your 2) ;)

& when i look at the code it feels like total gibberish to me,
i wish i had your brain ahaha ))

You've told me you had implemented attachment saving feature But..
added: "there might be some bugs", so for me, as long as you know what
type of bugs i might go through, i can't officially use it before you're certain
those bugs you believe that could happen aren't fixed. I cannot have an image
in its data affected & save it like that with alteration of that image & tell myself
it's ok, it's just a "bug", you know ? ))

So please make sure no bug would arrive before confirming it's updated again.
As with your previous mention, v1.3 remains a beta.

Can you make thunderbird recognize and open eml files from windows folders ?
& not from a thunderbird button.. just like what x-unsent addon by lieser does ?

So next time i have an issue, i won't kill myself spending days trying to obtain updates
that never happen, & i'm sure one person can help and not 2 people with 2 different addons.
Cause Lieser hasn't helped in 10 years & he's now proved me again, he prefers ignoring 
my requests instead of adding fixes.

for x-unsent support, he's just updated his addon to a webextension, & he's also told me 
he could add X-Priority by a workaround but he didn't do it nor shared a way to do it with you
as i've requested to him.

If you think it's too complicated to make your addon open emls from windows folders directly &
not tb's button. i'll be compelled to use both addons then.

Please make sure there could be no bugs in saving attachments in terms of data-integrity.
& try to find a workaround for X-Priority, otherwise, i end up doing what i've done since
years, opening saved emls with a text editor & go place the string myself all the time,
& this drives "one" nuts. I've been doing this since a decade.

As i've told you, i'll paypal you 20 euros, once it's finished. & as i've told you too,
it might be nothing for you, it's just a gesture, but, for me being on gov's help
& jobless, it's still money. with 20 euros, i buy 20 liters of orange juice, when 
i do trash cans to eat ((
